export type Locale = 'tr' | 'en';

type TranslationValue = string | ((values?: Record<string, unknown>) => string);

const en: Record<string, TranslationValue> = {
  dashboard: 'Dashboard',
  homeSubtitle: 'Review RPA projects, find issues, and improve automation quality.',
  projectWorkspace: 'UiPath project analysis workspace',
  globalSearch: 'Search workflows, findings, reports...',
  primaryNavigation: 'Primary navigation',
  home: 'Home',
  projects: 'Projects',
  findingsNav: 'Findings',
  reports: 'Reports',
  codeReview: 'Code Review',
  reviewHistory: 'Review History',
  settings: 'Settings',
  help: 'Help',
  appearance: 'Appearance',
  theme: 'Theme',
  profileSettings: 'Profile',
  languageSettings: 'Language',
  aiPreferences: 'AI Preferences',
  reviewRules: 'Review Rules',
  rules: 'Rules',
  activeRules: 'Active Rules',
  activeRulesHint: (v) => `Rules currently applied by the ${v?.profile ?? 'selected'} profile.`,
  activeProfile: 'Active analysis profile',
  profileRulesSummary: 'Active profile rule summary',
  filteredRuleCount: (v) => `${v?.count ?? 0} rules shown`,
  profileRuleCount: (v) => `${v?.count ?? 0} active in this profile`,
  profileConfiguredRuleCount: (v) => `${v?.count ?? 0} configured in this profile`,
  allSeverities: 'All severities',
  allSources: 'All sources',
  clearFilters: 'Clear filters',
  resizePanel: 'Resize panel',
  resetPanelWidth: 'Reset panel width',
  effectiveSeverity: 'Effective severity',
  scoreImpact: 'Score impact',
  maxPenaltyShort: (v) => `Max ${v?.value ?? 0}`,
  projectCompatibility: 'Project compatibility',
  allProjectTypes: 'All project types',
  ruleCatalog: 'Rule Catalog',
  ruleManagement: 'Rule management',
  totalRules: 'Total Rules',
  totalRulesHint: 'All rules in this profile',
  enabledRules: 'Enabled Rules',
  enabledRulesHint: 'Evaluated during analysis',
  disabledRules: 'Disabled Rules',
  disabledRulesHint: 'Temporarily excluded',
  customRulesHint: 'Created by users',
  editProfile: 'Edit Profile',
  rulesWorkspaceHelp: 'Review active profile rules, scoring settings, and project compatibility in one place.',
  ruleCatalogLoadFailed: 'Rule catalog could not be loaded.',
  searchRules: 'Search rules...',
  searchFindings: 'Search findings...',
  findingSort: 'Finding sort order',
  defaultOrder: 'Default order',
  severityHighToLow: 'Severity: high to low',
  severityLowToHigh: 'Severity: low to high',
  allRules: 'All rules',
  allCategories: 'All categories',
  findingCategory: 'Finding category',
  projectProfileHint: 'This project will remember the selected analysis profile.',
  categoryReliability: 'Reliability',
  categoryMaintainability: 'Maintainability',
  categoryPerformance: 'Performance',
  categorySecurity: 'Security',
  categoryExceptionHandling: 'Exception Handling',
  categoryNaming: 'Naming',
  categoryLogging: 'Logging',
  categoryUiAutomation: 'UI Automation',
  categoryArchitecture: 'Architecture',
  categoryConfiguration: 'Configuration',
  categoryOrchestrator: 'Orchestrator',
  enabled: 'Enabled',
  disabled: 'Disabled',
  source: 'Source',
  builtIn: 'Built-in',
  custom: 'Custom',
  builtInRule: 'Built-in rule',
  customRule: 'Custom rule',
  ruleId: 'Rule ID',
  ruleName: 'Rule Name',
  severity: 'Severity',
  weight: 'Weight',
  fixSupport: 'Fix support',
  aggregationSupport: 'Aggregation support',
  selectRule: 'Select a rule to view details.',
  loadingRules: 'Loading rules...',
  exportRules: 'Export Rules',
  importRules: 'Import Rules',
  customRuleBuilder: 'Custom Rule Builder',
  createRule: 'Create Rule',
  newCustomRule: 'New Custom Rule',
  description: 'Description',
  recommendation: 'Recommendation',
  matchMode: 'Match Mode',
  conditions: 'Conditions',
  caseSensitive: 'Case sensitive',
  remove: 'Remove',
  addCondition: 'Add Condition',
  testRule: 'Test Rule',
  saveRule: 'Save Rule',
  testing: 'Testing...',
  saving: 'Saving...',
  customRuleNeedsProject: 'Enter or analyze a UiPath project path before testing this rule.',
  customRuleTestCompleted: 'Custom rule test completed.',
  customRuleTestFailed: 'Custom rule test failed.',
  customRuleSaved: 'Custom rule saved.',
  customRuleSaveFailed: 'Custom rule could not be saved.',
  ruleTemplates: 'Rule Templates',
  reuseRuleTemplate: 'Reuse a rule template',
  allTemplates: 'All Templates',
  builtInTemplates: 'Built-in Templates',
  analysisProfileTemplates: 'Analysis Profile Templates',
  myTemplates: 'My Templates',
  saveAsTemplate: 'Save as Template',
  templateSource: 'Template source',
  ruleTemplate: 'Template',
  ruleSource: 'Rule source',
  builtInRules: 'Built-in Rules',
  customRules: 'Custom Rules',
  noTemplate: 'No Template',
  noCustomTemplates: 'No custom templates have been created yet.',
  noTemplatesMatchFilter: 'No templates match this filter.',
  noActiveRulesMatchFilter: 'No active rules match this filter.',
  ruleTemplateSaved: (v) => v?.templateName ? `Rule template "${v.templateName}" was saved successfully.` : 'Rule template saved successfully.',
  ruleTemplateSaveFailed: 'Rule template could not be saved.',
  ruleTemplateDuplicate: 'A rule template with this name already exists.',
  dismissNotification: 'Dismiss notification',
  customRulesExported: 'Custom rules exported.',
  customRulesImported: 'Custom rules imported.',
  customRulesImportFailed: 'Custom rules import failed.',
  pasteCustomRulesJson: 'Paste custom-rules JSON.',
  ruleNoiseWarning: 'This rule may create excessive noise.',
  testRuleResult: 'Test Rule Result',
  customRuleMatches: (v) => `This rule matches ${v?.activities ?? 0} activities across ${v?.workflows ?? 0} workflows. Estimated findings: ${v?.findings ?? 0}.`,
  allProjects: 'All projects',
  historyProjectFilter: 'History project filter',
  projectHistoryOnly: 'Showing analysis snapshots for the selected project.',
  notifications: 'Notifications',
  about: 'About',
  lightTheme: 'Light',
  darkTheme: 'Dark',
  systemTheme: 'System',
  aiReviewEnabled: 'AI Review Enabled',
  autoReviewSummary: 'Automatically Generate Review Summary',
  suggestedFixes: 'Suggested Fixes',
  askProjectEnabled: 'Ask Project',
  selectorQuality: 'Selector Quality',
  exceptionHandling: 'Exception Handling',
  logging: 'Logging',
  namingConvention: 'Naming Convention',
  hardcodedValues: 'Hardcoded Values',
  performance: 'Performance',
  maintainability: 'Maintainability',
  security: 'Security',
  reframeworkBestPractices: 'REFramework Best Practices',
  settingsNotice: 'This section is prepared for the desktop MVP; persistent preferences can be connected to a profile in a later release.',
  projectIntake: 'Project intake',
  backendChecking: 'Checking backend...',
  backendReady: (v) => `Backend ready at ${v?.url ?? ''}`,
  backendUnavailable: 'RPA Dev Assistant backend could not be started.',
  uipathProject: 'UiPath Project',
  browse: 'Browse',
  browseTitleDesktop: 'Select UiPath project folder',
  browseTitleBrowser: 'Browse is available in the desktop app',
  analysisProfile: 'Analysis Profile',
  browserModeHint: 'Browser development mode: native folder selection is available in the desktop app. Manual path entry still works.',
  noFolderSelected: 'No folder selected',
  manualPathEntered: 'Manual path entered. Full validation runs during analysis.',
  folderSelected: 'Folder selected. project.json validation is ready.',
  folderSelectedProjectJson: 'Folder selected. project.json detected.',
  notUipathProject: 'This folder does not appear to be a UiPath project.',
  validationFailed: 'Folder selected. Project validation could not be completed.',
  selectProjectFirst: 'Select or enter a UiPath project folder first.',
  backendNotReady: 'Backend is not ready yet.',
  analysisCompleted: 'Analysis completed.',
  folderSelectedBackendNotReady: 'Folder selected. Backend is not ready for project validation yet.',
  analysisFailed: 'Project analysis failed. Check the selected folder and backend status.',
  analyzeProject: 'Analyze Project',
  dashboardAnalyzeProject: 'Dashboard primary action',
  analyzing: 'Analyzing...',
  exportJson: 'Export JSON',
  exportHtml: 'Export HTML',
  exportPdf: 'Export PDF',
  exporting: 'Exporting...',
  createReport: 'Create Report',
  reportDialogTitle: 'Create Report',
  reportExecutiveSummary: 'Executive Summary',
  reportQualityScore: 'Quality Score',
  reportWorkflowDetails: 'Workflow Details',
  reportAiRecommendations: 'AI Recommendations',
  reportFixSuggestions: 'Fix Suggestions',
  cancel: 'Cancel',
  createHtmlReport: 'Create HTML Report',
  runAiProjectReview: 'Run AI Project Review',
  staticAnalysisBeforeAi: 'Run static analysis before starting AI review.',
  staticAnalysisBeforeAsk: 'Run static analysis before asking project questions.',
  enterProjectQuestion: 'Enter a project question first.',
  aiAssistedAnswerCompleted: 'AI-assisted answer completed.',
  aiReviewCompleted: 'AI review completed.',
  aiReviewFailed: 'AI review failed.',
  askProjectFailed: 'Ask Project failed.',
  fixSuggestionGenerated: 'Fix suggestion generated.',
  fixSuggestionFailed: 'Fix suggestion failed.',
  applyFixFailed: 'Apply fix failed.',
  undoFailed: 'Undo failed.',
  analysisBeforeExport: 'Run an analysis before exporting a report.',
  reportExportFailed: (v) => `${v?.format ?? 'Report'} export failed.`,
  analyzingWithAi: 'Analyzing with AI...',
  overview: 'Overview',
  changeHistory: 'Change History',
  workflows: 'Workflows',
  report: 'Report',
  aiReview: 'AI Review',
  askProject: 'Ask Project',
  processPddNav: 'Process & PDD Analysis',
  processPddEyebrow: 'Process Understanding',
  processPddTitle: 'Process & PDD Analysis',
  processPddHelp: 'Understand the analyzed process, extract evidence-backed business rules, and compare them with a selected PDD.',
  processPddAnalyzeFirst: 'Select and analyze a UiPath project first.',
  pddDocument: 'PDD Document',
  selectPdd: 'Select a PDD document',
  processPddSupportedFormats: 'TXT and Markdown are supported in this safe local version. The source document is never modified.',
  processPddAnalyze: 'Analyze Process & PDD',
  processPddAnalyzing: 'Analyzing process and PDD...',
  processPddFailed: 'Process and PDD analysis failed.',
  processPddReadOnly: 'Read-only comparison. No project or PDD file is modified.',
  identifiedSystems: 'Identified Systems',
  projectBusinessRules: 'Project Business Rules',
  pddBusinessRules: 'PDD Business Rules',
  possiblyMissingRules: 'Possibly Missing Rules',
  processSummary: 'Process Summary',
  systemsUsed: 'Systems Used',
  processSystem: 'System',
  processSystemType: 'Type',
  processEvidence: 'Evidence',
  processUsedByWorkflows: 'Used by Workflows',
  processFlow: 'Process Flow',
  processFlowDisclaimer: 'This order summarizes static Invoke Workflow File relationships. Runtime branch or parallel execution order is not inferred.',
  processFlowOmitted: '{count} additional invoked workflows are omitted from this short summary.',
  evidenceBackedRules: 'Only conditions supported by workflow evidence are shown.',
  processConfidence: 'Confidence',
  processRuleStatus: 'Documentation status',
  allConfidence: 'All confidence levels',
  processAllWorkflows: 'All workflows',
  pddGapAnalysis: 'PDD Gap Analysis',
  gapAnalysisDisclaimer: 'Possible gaps are suggestions for review, not definitive documentation errors.',
  processStatus: 'Status',
  allStatuses: 'All statuses',
  possiblyMissingFromPdd: 'Possibly Missing from PDD',
  possiblyDocumented: 'Possibly Documented',
  needsReview: 'Needs Review',
  documented: 'Documented',
  pddStatusPossiblyMissing: 'Possibly Missing from PDD',
  pddStatusPossiblyDocumented: 'Possibly Documented',
  pddStatusNeedsReview: 'Needs Review',
  pddStatusDocumented: 'Documented',
  pddAdditionSuggestion: 'Suggested PDD Addition',
  matchedPddEvidence: 'Matching PDD Evidence',
  noMatchingBusinessRules: 'No business rules match the selected filters.',
  noPddBusinessRules: 'No documented business rules were identified in the selected PDD.',
  noEvidenceFound: 'No supported evidence was identified.',
  projectOverview: 'Project Overview',
  grade: 'Grade',
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
  passedChecks: 'Passed Checks',
  project: 'Project',
  activities: 'Activities',
  score: 'Score',
  summary: 'Summary',
  profile: 'Profile',
  errors: 'Errors',
  warnings: 'Warnings',
  suggestions: 'Suggestions',
  reviewSummary: 'Review Summary',
  noIssuesSummary: 'The project passed the active deterministic review rules. No critical finding is visible.',
  reviewSummaryText: (v) => `Project analyzed. Main focus areas are ${v?.categories ?? 'maintainability and reliability'}. Review the Findings tab for details.`,
  topIssues: 'Top Issues',
  workflowHealth: 'Workflow Health',
  noIssuesDetected: 'No issues detected by the active rule profile.',
  all: 'All',
  category: 'Category',
  dependencies: 'Dependencies',
  configAnalysis: 'Config Analysis',
  configIntelligenceTitle: 'Config Intelligence',
  configIntelligenceHelp: 'Analyze Config.xlsx usage, find unused keys, missing references, and safe hard-coded Config candidates.',
  configReady: 'Config analyzed',
  configOverviewTitle: 'Analysis overview',
  configOverviewHelp: 'Review Config coverage and open a result area to investigate details.',
  analyzedConfig: 'Analyzed workbook',
  reviewSelectedChanges: (v) => `Review changes (${v?.count ?? 0})`,
  selectedChangesSummary: (v) => `${v?.count ?? 0} selected changes will be included in this preview.`,
  refreshPreview: 'Refresh preview',
  configAnalysisEmptyTitle: 'No Config analysis yet',
  analyzeConfig: 'Analyze Config',
  configAnalysisCompleted: 'Config analysis completed.',
  configAnalysisFailed: 'Config analysis failed.',
  configAnalysisEmpty: 'Run Config analysis for the selected UiPath project.',
  configWorkbook: 'Config Workbook',
  configWorkbookAutoDetect: 'Auto-detect Config.xlsx or choose manually',
  configWorkbookHint: 'Leave empty to auto-detect Data/Config.xlsx. Choose a file when the project uses a custom Config location.',
  browseConfigWorkbook: 'Select Config workbook',
  configWorkbookSelected: 'Config workbook selected.',
  configBrowserFileHint: 'Desktop file picker is unavailable in browser mode. Enter the Config workbook path manually.',
  configWorkbookNotFound: 'Config.xlsx was not found for this project.',
  configInUse: (v) => `Config in use: ${v?.fileName ?? ''}`,
  selectedConfigInvalid: 'The selected Config file could not be read or does not use a supported Config structure.',
  configKeys: 'Config Keys',
  usedConfigKeys: 'Used Config Keys',
  configUsageGraph: 'Usage Graph',
  configUsageGraphHelp: 'Config key to workflow/activity relationships from parsed workflow references.',
  noConfigUsages: 'No Config key usages were detected.',
  usageCount: (v) => `${v?.count ?? 0} usages`,
  configActivityCount: (v) => `${v?.count ?? 0} activities`,
  unusedConfig: 'Unused Config',
  unusedConfigHelp: 'Keys listed here exist in Config but were not referenced by parsed workflow properties or expressions. Removals are never preselected.',
  searchUnusedConfig: 'Search unused Config keys...',
  showingUnusedConfig: (v) => `${v?.shown ?? 0} of ${v?.total ?? 0} unused keys shown`,
  configSheetAndRow: (v) => `${v?.sheet ?? '-'} sheet · row ${v?.row ?? '-'}`,
  noParsedConfigReference: 'No parsed workflow reference was found for this key.',
  missingConfig: 'Missing Config',
  missingConfigHelp: 'Keys listed here are referenced by workflows but are not present in Config.',
  hardcodedCandidates: 'Hard-coded Candidates',
  hardcodedCandidatesHelp: 'Conservative literal values that may belong in Config. Sensitive values are redacted and are not suggested for plain Config.',
  changePreview: 'Change Preview',
  previewConfigChanges: 'Preview Changes',
  configPreviewReady: 'Config change preview is ready.',
  configPreviewInvalid: 'Config change preview has validation issues.',
  configPreviewFailed: 'Config change preview failed.',
  runConfigAnalysisFirst: 'Run Config analysis first.',
  noUnusedConfig: 'No unused Config keys were detected.',
  noMissingConfig: 'No missing Config references were detected.',
  noHardcodedCandidates: 'No hard-coded Config candidates were detected.',
  noConfigPreview: 'Select Config changes and preview them before generating a workbook.',
  configOutputPath: 'Output Config path',
  configOutputPathRequired: 'Choose an output Config path before generating.',
  configBrowserOutputHint: 'Desktop Save dialog is unavailable in browser mode. Enter an output path manually.',
  configOriginalUnchanged: 'The original Config workbook is never modified. A new workbook is generated with Save As.',
  generateConfigWorkbook: 'Generate Config Workbook',
  configGenerateCompleted: 'The new Config file was saved successfully.',
  configGenerateFailed: 'Config workbook generation failed.',
  configGeneratedAt: (v) => `Config workbook generated at ${v?.path ?? ''}.`,
  dependencyAnalysis: 'Dependency Analysis',
  dependencyAnalysisHelp: 'Offline-first package usage, risk, and compatibility signals from project.json and parsed activities.',
  usedDependencies: 'Used',
  uiPathDependencies: 'UiPath Packages',
  thirdPartyDependencies: 'Third-party',
  possiblyUnused: 'Possibly Unused',
  potentialConflicts: 'Potential Conflicts',
  modernClassicMode: 'Modern / Classic Mode',
  searchPackages: 'Search packages...',
  package: 'Package',
  version: 'Version',
  usage: 'Usage',
  usedByWorkflows: 'Used By Workflows',
  dependencyDetail: 'Dependency Detail',
  compatibilityStatus: 'Compatibility',
  versionStatus: 'Version Status',
  usedActivities: 'Used Activities',
  noMappedActivities: 'No mapped activities found.',
  noMappedWorkflows: 'No mapped workflows found.',
  compatibilityNotes: 'Compatibility Notes',
  noDependencyRisks: 'No dependency risk notes.',
  noRelatedFindings: 'No related findings.',
  noDependencyAnalysis: 'Dependency analysis was not produced.',
  dependenciesUsed: 'Dependencies Used',
  noDependenciesUsed: 'No dependency usage was mapped for this workflow.',
  close: 'Close',
  flowchartConverter: 'Flowchart Converter',
  standaloneTool: 'Standalone tool',
  flowchartConverterHelp: 'Analyze individual UiPath XAML files, preview Flowchart → Sequence conversion, and save the converted workflow as a new file.',
  conversionProgress: 'Flowchart conversion progress',
  converterStepSelect: 'Select and analyze',
  converterStepSelectHint: 'Choose XAML',
  converterStepSelectDescription: 'Select one or more UiPath XAML files, then analyze their workflow structure.',
  converterStepAssess: 'Review readiness',
  converterStepAssessHint: 'Check complexity',
  converterStepAssessDescription: 'Review structure, complexity, confidence, risks, and unsupported patterns before conversion.',
  converterStepPreview: 'Preview and save',
  converterStepPreviewHint: 'Save as a new file',
  converterStepPreviewDescription: 'Compare the current Flowchart with the proposed Sequence and choose where to save the result.',
  selectedFileCount: (v) => `${v?.count ?? 0} file selected`,
  xamlAnalysisCompleted: (v) => `${v?.count ?? 0} XAML file analyzed successfully.`,
  assessmentReasons: 'Assessment reasons',
  flowchartReasonLinear: 'The Flowchart is linear and has no cycles or unreachable nodes.',
  flowchartReasonSimpleDecision: 'The Flowchart has a simple acyclic decision structure.',
  flowchartReasonReviewBranches: 'The Flowchart can be previewed, but branch and merge behavior should be reviewed in UiPath Studio.',
  flowchartReasonLoopReview: 'The Flowchart contains loop or back-edge control flow and requires careful review after conversion.',
  flowchartRiskCycle: 'A cycle was detected. Flowchart cycles can represent While, Retry, or goto-like control flow.',
  flowchartRiskUnreachable: 'An unreachable node was detected from the Flowchart start node.',
  flowchartRiskMultipleEntries: (v) => `Multiple entry-like nodes were detected: ${v?.count ?? 0}.`,
  flowchartUnsupportedNoNodes: 'No Flowchart nodes could be parsed.',
  flowchartUnsupportedDecisionTarget: (v) => `FlowDecision branch targets could not be resolved for node ${v?.node ?? '-'}.`,
  flowchartUnsupportedSwitchTarget: (v) => `FlowSwitch case targets could not be resolved for node ${v?.node ?? '-'}.`,
  flowchartUnsupportedNodeCount: (v) => `Unsupported Flowchart node count: ${v?.count ?? 0}.`,
  flowchartNestedMessage: (v) => `A nested Flowchart was detected inside a ${v?.structure ?? '-'} workflow. Review the generated preview carefully before using it in production.`,
  flowchartStepCreateSequence: 'Create a Sequence root.',
  flowchartStepPreserveContent: 'Preserve workflow arguments, variables, activity properties, and expressions.',
  flowchartStepMoveActivities: 'Move linear FlowStep activities into Sequence order.',
  flowchartStepDecision: 'Represent FlowDecision branches as If preview nodes.',
  flowchartStepSwitch: 'Represent FlowSwitch branches as Switch preview nodes.',
  flowchartStepMerge: 'Keep shared merge nodes as continuation activities after branch previews.',
  flowchartStepLoop: 'Represent recognized back-edge loops as While preview nodes and review them in UiPath Studio.',
  flowchartStepExcludeComments: 'Exclude commented-out activity blocks from the generated Sequence.',
  flowchartNestedDetected: 'A nested Flowchart was detected inside a non-Flowchart workflow.',
  flowchartRootOnlySupported: 'Automatic conversion currently supports only workflows whose root activity is Flowchart.',
  selectAndAnalyzeBeforePreview: 'Select and analyze a XAML file to create a conversion preview.',
  xamlFilePath: 'XAML File Path',
  selectXamlFirst: 'Select or enter a UiPath .xaml file first.',
  selectXamlFile: 'Select XAML File',
  noXamlFileSelected: 'No XAML file selected',
  xamlFileSelected: 'XAML file selected',
  analyzeXaml: 'Analyze XAML',
  selectedXamlFiles: 'Selected XAML Files',
  flowchartConverterEmpty: 'Select one or more .xaml workflow files to inspect Flowchart conversion readiness.',
  standaloneContext: 'Standalone Context',
  standaloneBrowserModeHint: 'Browser mode cannot open native file dialogs. Manual file path entry still works when the backend can access that path.',
  standaloneFlowchartAnalyzeFailed: 'Standalone Flowchart analysis failed.',
  standaloneFlowchartConvertFailed: 'Standalone Flowchart conversion failed.',
  flowchartConverterDetail: 'Flowchart converter detail',
  originalFileNotModified: 'The original XAML file is never modified by this standalone flow.',
  saveConvertedWorkflowAs: 'Save Converted Workflow As...',
  outputXamlPath: 'Output XAML path',
  chooseOutputPath: 'Choose Save Location',
  chooseOutputPathFirst: 'Choose where the converted .xaml file will be saved.',
  outputXamlPathRequired: 'Choose an output XAML path before converting.',
  convertAndSave: 'Convert and Save',
  convertedWorkflowSaved: 'Converted workflow saved successfully.',
  conversionNotAvailable: 'Conversion is not available for this file',
  conversionNotAvailableReason: 'This workflow cannot be converted safely by the standalone converter.',
  conversionNotAvailableNestedReason: 'A Flowchart was detected inside another workflow structure. Save As is enabled only when that nested Flowchart can be converted safely without changing the surrounding workflow root.',
  detectedFlowchartNodes: 'Detected Flowchart Nodes',
  standaloneFlowchartStatusReady: 'Ready',
  standaloneFlowchartStatusAlreadySequence: 'Already Sequence',
  standaloneFlowchartStatusRequiresReview: 'Requires Review',
  standaloneFlowchartStatusComplex: 'Complex',
  standaloneFlowchartStatusUnsupported: 'Unsupported',
  standaloneFlowchartStatusConverted: 'Converted',
  standaloneFlowchartStatusFailed: 'Failed',
  xamlPathRequired: 'Enter a XAML file path first.',
  visualWorkflowPreview: 'Visual Workflow Preview',
  visualFlow: 'Visual Flow',
  xamlCodePreview: 'XAML Code Preview',
  activitiesToUse: 'Activities to be Used',
  activitiesUsedCount: (v) => `${v?.count ?? 0} activities in sequence`,
  copyXamlCode: 'Copy XAML',
  copiedToClipboard: 'Copied to clipboard!',
  workflowTargetSequence: 'Target: Sequence Workflow',
  activitySourceNode: 'Source Node',
  activityRole: 'Role',
  executableActivity: 'Executable Activity',
  containerActivity: 'Container',
  controlFlowActivity: 'Control Flow',
  customDependencyDetected: 'Custom Dependency Activities Detected',
  customDependencyNotice: (v) => `${v?.count ?? 0} custom / third-party dependency activity/activities found in this Flowchart.`,
  replaceWithStandardUiPath: 'Replace with Standard UiPath Activities',
  replaceWithStandardUiPathHelp: 'When enabled, custom dependency activities will be converted into standard UiPath activities in the output XAML.',
  suggestedReplacement: 'Suggested Replacement',
  customActivityName: 'Custom Activity',
  suggestedPackage: 'Suggested Package',
  replacementReason: 'Reason / Mapping',
  flowchartConversionSummary: 'Conversion Summary',
  structureType: 'Structure Type',
  containsFlowchart: 'Contains Flowchart',
  flowchartCount: 'Flowchart Count',
  flowchartConversion: 'Flowchart Conversion',
  previewConversion: 'Preview Conversion',
  copyPlan: 'Copy Plan',
  conversionPreviewOnly: 'Read-only conversion preview. No XAML file will be modified.',
  nestedFlowchartConversionNotSupported: 'Nested Flowchart detected. Automatic conversion is currently available only when the workflow root is Flowchart.',
  flowchartConversionFailed: 'Flowchart conversion analysis failed.',
  currentStructure: 'Current Structure',
  convertibility: 'Convertibility',
  nodes: 'Nodes',
  decisions: 'Decisions',
  switches: 'Switches',
  cycles: 'Cycles',
  unreachableNodes: 'Unreachable Nodes',
  currentFlowchart: 'Current Flowchart',
  proposedSequence: 'Proposed Sequence',
  noPreviewAvailable: 'No conversion preview is available.',
  noRisks: 'No conversion risks detected.',
  unsupportedPatterns: 'Unsupported Patterns',
  noUnsupportedPatterns: 'No unsupported patterns detected.',
  conversionMappings: 'Conversion Mappings',
  sourceNode: 'Source Node',
  targetPath: 'Target Path',
  flowchartLevelSafe: 'Safe',
  flowchartLevelRequiresReview: 'Requires Review',
  flowchartLevelComplex: 'Complex',
  flowchartLevelNotSupported: 'Not Supported',
  flowchartConfidenceHigh: 'High',
  flowchartConfidenceMedium: 'Medium',
  flowchartConfidenceLow: 'Low',
  applyConversion: 'Apply Conversion',
  confirmConversion: 'Confirm Conversion',
  rollback: 'Rollback',
  rollingBack: 'Rolling back...',
  conversionApplyWarning: 'This will modify the workflow XAML file. A backup will be created automatically before the change.',
  conversionBackupWillBeCreated: 'A backup will be created automatically before the workflow is modified.',
  conversionManualReviewOnly: 'This conversion is preview-only because the Flowchart requires manual review or is not supported for automatic apply.',
  manualReviewRequired: 'Manual review required',
  flowchartConversionApplyFailed: 'Flowchart conversion apply failed.',
  flowchartConversionRollbackFailed: 'Flowchart conversion rollback failed.',
  conversionAppliedSuccessfully: 'Flowchart conversion applied successfully.',
  conversionWasNotApplied: 'Flowchart conversion was not applied.',
  conversionRolledBackSuccessfully: 'Conversion rolled back successfully.',
  showingFindings: (v) => `${v?.shown ?? 0} / ${v?.total ?? 0} findings shown`,
  noFilteredFindings: 'No important issue was detected or the current filter returned no findings.',
  showMoreFindings: (v) => `Show more (${v?.remaining ?? 0} remaining)`,
  affectedActivities: 'affected activities',
  relevantActivities: 'relevant activities',
  fixSuggestion: 'Fix Suggestion',
  rule: 'Rule',
  reviewLowConfidenceFix: 'Review this suggestion carefully before making changes.',
  aiSuggestionManualReview: 'AI suggestion — manual review required.',
  fixSuggestionStale: 'Fix suggestion was generated but may be stale.',
  applying: 'Applying...',
  applyFix: 'Apply Fix',
  fixAppliedSuccessfully: 'Fix applied successfully.',
  fixWasNotApplied: 'Fix was not applied.',
  backupCreated: 'Backup created',
  projectFilesChangedReanalysis: 'Project files changed. Re-run analysis to refresh findings.',
  applyThisChange: 'Apply this change?',
  property: 'Property',
  unknown: 'Unknown',
  backupWillBeCreated: 'A backup will be created before the file is modified.',
  generating: 'Generating...',
  suggestedFix: 'Suggested Fix',
  noFixAvailable: 'No automated fix suggestion is available for this finding yet.',
  aiFixPrivacy: 'A minimized, redacted workflow context will be sent to the configured AI provider.',
  generateAiSuggestion: 'Generate AI-assisted suggestion',
  fixType: 'Fix Type',
  fixability: 'Fixability',
  risk: 'Risk',
  confidence: 'Confidence',
  aiAssisted: 'AI Assisted',
  autoApply: 'Auto Apply',
  yes: 'Yes',
  no: 'No',
  available: 'Available',
  previewOnly: 'Preview only',
  before: 'BEFORE',
  after: 'AFTER',
  why: 'Why?',
  steps: 'Steps',
  risks: 'Risks',
  userInputNeeded: 'User Input Needed',
  validationNotes: 'Validation Notes',
  copyFixInstructions: 'Copy Fix Instructions',
  manualChangeRequired: 'Manual change required.',
  highRiskFix: 'This suggestion may affect workflow behavior. Review it carefully in UiPath Studio.',
  noBeforePreview: 'No before preview available.',
  noAfterPreview: 'No after preview available.',
  workflowCountFound: (v) => `${v?.count ?? 0} Workflows Found`,
  workflowListHelp: 'Search, filter, and inspect workflow details.',
  searchWorkflows: 'Search workflows...',
  byFindings: 'By findings',
  byActivity: 'By activity',
  byName: 'By name',
  workflowName: 'Workflow Name',
  type: 'Type',
  activity: 'Activity',
  status: 'Status',
  good: 'Good',
  reviewNeeded: 'Review',
  risky: 'Risky',
  workflowDetail: 'Workflow detail',
  backToWorkflows: 'Back to Workflows',
  fileName: 'File Name',
  relativePath: 'Relative Path',
  activityCount: 'Activity Count',
  executableActivityCount: 'Executable Activity Count',
  findingCount: 'Finding Count',
  arguments: 'Arguments',
  noArguments: 'No arguments were found for this workflow.',
  direction: 'Direction',
  name: 'Name',
  invokedWorkflows: 'Invoked Workflows',
  noInvokes: 'This workflow does not directly call another workflow.',
  dynamicWorkflowReference: 'Dynamic workflow reference',
  calledBy: 'Called By',
  noCallers: 'This workflow is not called by another workflow.',
  activityTypes: 'Activity Types',
  activityTree: 'Activity Tree',
  noActivities: 'No parsed activities were found for this workflow.',
  selectedActivity: 'Selected Activity',
  properties: 'Properties',
  relatedFindings: 'Related Findings',
  workflowFindings: 'Workflow Findings',
  noWorkflowFindings: 'No findings were linked to this workflow.',
  reviewWorkflowWithAi: 'Review Workflow with AI',
  aiNotConfigured: 'AI Review is not configured.',
  aiPanelTitle: 'Ask a question about this project or start an AI-assisted review.',
  aiReviewInterpretationNotice: 'AI review provides additional interpretation and recommendations. Deterministic static analysis findings remain the primary source of rule-based issues.',
  aiReviewPrivacyNotice: 'AI Review sends a minimized, redacted project summary to the configured AI provider.',
  aiReviewEmptyState: 'Run an AI project review or choose a workflow from the Workflows tab.',
  aiQuickRiskSummary: 'Summarize the biggest risks',
  aiQuickRefactorWorkflows: 'Which workflows should be refactored?',
  aiQuickSelectors: 'Show selector problems',
  aiQuickExceptionHandling: 'Find exception handling issues',
  aiQuickMaintainability: 'How can I improve project maintainability?',
  aiQuickTopFindings: 'Explain the top 5 critical findings',
  riskLevel: 'Risk Level',
  scope: 'Scope',
  model: 'Model',
  aiReviewSummary: 'AI Review Summary',
  strengths: 'Strengths',
  issues: 'Issues',
  noAiIssues: 'No AI issues returned.',
  evidenceLabel: 'Evidence',
  relatedDeterministicRules: 'Related deterministic rules',
  recommendations: 'Recommendations',
  architectureObservations: 'Architecture Observations',
  noItemsReturned: 'No items returned.',
  askNotice: 'Direct project lookup is performed locally. Questions requiring interpretation may send a minimized, redacted evidence set to the configured AI provider.',
  askLabel: 'Ask your UiPath project',
  askPlaceholder: 'Which workflow has the highest exception handling risk?',
  ask: 'Ask',
  asking: 'Asking...',
  suggestedQuestions: 'Suggested Questions',
  suggestedQueueQuestion: 'Where are Queue activities used?',
  suggestedDelayQuestion: 'Which workflows contain Delay?',
  suggestedMostFindingsQuestion: 'Which workflow has the most findings?',
  suggestedProcessQuestion: 'Explain Process.xaml',
  suggestedInvocationQuestion: 'Show workflow invocation relationships',
  suggestedExceptionQuestion: 'Which workflows have exception handling issues?',
  answer: 'Answer',
  questionConfidence: 'Confidence',
  aiUsed: 'AI Used',
  answeredLocal: 'Answered from local project analysis',
  aiAnswerBased: 'AI-assisted answer based on retrieved project evidence',
  evidence: 'Evidence',
  relatedWorkflows: 'Related Workflows',
  relatedRules: 'Related Rules',
  reasoningSummary: 'Reasoning Summary',
  value: 'Value',
  current: 'Current',
  restore: 'Restore',
  undo: 'Undo',
  undoUnavailable: 'Undo unavailable.',
  undoThisChange: 'Undo this change?',
  undoChange: 'Undo Change',
  undoing: 'Undoing...',
  changeRestoredSuccessfully: 'Change restored successfully.',
  changeWasNotRestored: 'Change was not restored.',
  safetyBackupCreated: 'Safety backup created',
  reanalysisRequired: 'Reanalysis required.',
  noFixHistory: 'No RPA Dev Assistant fix history was found for this project.',
  analysisHistory: 'Analysis History',
  allProjectsHistory: 'Showing analysis snapshots from all evaluated projects.',
  noAnalysisHistory: 'No saved analysis snapshots were found for this project.',
  comparePrevious: 'Compare Previous',
  noPreviousSnapshot: 'No previous snapshot',
  beforeAfterComparison: 'Before / After Comparison',
  scoreChange: 'Score Change',
  findingChange: 'Finding Change',
  newFindings: 'New Findings',
  resolvedFindings: 'Resolved Findings',
  unchangedFindings: 'Unchanged Findings',
  changedFindings: 'Changed Findings',
  workflowChanges: 'Workflow Changes',
  noWorkflowChanges: 'No workflow-level changes were detected.',
  activityChange: 'Activity Change',
  complexityChange: 'Complexity Change',
  fixHistory: 'Fix History',
  analysisHistoryLoadFailed: 'Analysis history could not be loaded.',
  analysisComparisonFailed: 'Analysis comparison could not be created.',
  none: 'None',
  loading: 'Loading...',
  refresh: 'Refresh',
  applied: 'Applied',
  unknownWorkflow: 'Unknown workflow',
  unknownRule: 'Unknown rule',
  analysisOutOfDate: 'Analysis out of date.',
  analysisOutOfDateDetail: 'Project files changed. Re-run analysis to refresh findings and quality score.',
  rerunAnalysis: 'Re-run Analysis',
  reportNotice: 'HTML and JSON exports use the current report infrastructure. PDF export is disabled in this version.',
  locale: 'Language',
  greeting: 'Good evening, Mina',
  openProject: 'Open Project',
  reviewedProjects: 'Reviewed Projects',
  openFindings: 'Open Findings',
  averageQualityScore: 'Average Quality Score',
  recentProjects: 'Recent Projects',
  projectColumn: 'PROJECT',
  platformColumn: 'PLATFORM',
  lastReviewColumn: 'LAST REVIEW',
  qualityScoreColumn: 'QUALITY SCORE',
  findingsColumn: 'FINDINGS',
  statusColumn: 'STATUS',
  todayTime: 'Today 14:32',
  yesterday: 'Yesterday',
  complexity: 'Complexity',
  workflowComplexity: 'Workflow Complexity',
  complexityDistribution: 'Complexity Distribution',
  topComplexWorkflows: 'Top Complex Workflows',
  complexityScore: 'Complexity Score',
  complexityLevel: 'Complexity Level',
  maxNestingDepth: 'Max Nesting Depth',
  decisionCount: 'Decision Count',
  loopCount: 'Loop Count',
  tryCatchCount: 'Try/Catch Count',
  invokeWorkflowCount: 'Invoke Workflow Count',
  containerActivityCount: 'Container Activity Count',
  whyThisScore: 'Why this score?',
  rawPenalty: 'Raw Penalty',
  normalizedPenalty: 'Normalized Penalty',
  projectSizeFactor: 'Project Size Factor',
  appliedPenalty: 'Applied Penalty',
  maxPenalty: 'Max Penalty',
  occurrenceCount: 'Occurrences',
  veryHigh: 'Very High',
  profileLoadFailed: 'Rule profiles could not be loaded.',
  customRuleProfiles: 'Custom Rule Profiles',
  profileBuilder: 'Profile Builder',
  exportProfiles: 'Export Profiles',
  saveProfile: 'Save Profile',
  profileId: 'Profile ID',
  profileName: 'Profile Name',
  profileTemplate: 'Profile Template',
  selectProfileTemplate: 'Select a profile template',
  severityOverride: 'Severity Override',
  defaultSeverity: 'Default Severity',
  namingConventionSettings: 'Naming convention settings',
  namingPattern: 'Naming pattern',
  namingPatternPlaceholder: 'Regular expression, for example ^[A-Z][A-Za-z0-9]*$',
  requiredPrefix: 'Required prefix',
  inArgumentPrefix: 'In argument prefix',
  outArgumentPrefix: 'Out argument prefix',
  inOutArgumentPrefix: 'In/Out argument prefix',
  ruleProfileSaved: 'Rule profile saved.',
  ruleProfileSaveFailed: 'Rule profile could not be saved.',
  ruleProfilesExported: 'Rule profiles exported.',
  ruleNameEn: 'Rule Name (EN)',
  ruleNameTr: 'Rule Name (TR)',
  descriptionEn: 'Description (EN)',
  descriptionTr: 'Description (TR)',
  recommendationEn: 'Recommendation (EN)',
  recommendationTr: 'Recommendation (TR)',
  propertyName: 'Property Name',
  compareValue: 'Compare Value',
};

const tr: Record<string, TranslationValue> = {
  dashboard: 'Ana Sayfa',
  homeSubtitle: 'RPA projelerinizi inceleyin, sorunları tespit edin ve otomasyon kalitesini artırın.',
  projectWorkspace: 'UiPath proje analiz çalışma alanı',
  globalSearch: 'Workflow, bulgu ve raporlarda ara...',
  primaryNavigation: 'Ana navigasyon',
  home: 'Ana Sayfa',
  projects: 'Projeler',
  findingsNav: 'Bulgular',
  reports: 'Raporlar',
  codeReview: 'Code Review',
  reviewHistory: 'İnceleme Geçmişi',
  settings: 'Ayarlar',
  help: 'Yardım',
  appearance: 'Görünüm',
  theme: 'Tema',
  profileSettings: 'Profil',
  languageSettings: 'Dil',
  aiPreferences: 'AI Tercihleri',
  reviewRules: 'Review Rules',
  rules: 'Kurallar',
  activeRules: 'Aktif Rule’lar',
  activeRulesHint: (v) => `${v?.profile ?? 'seçili'} profile tarafından şu an uygulanan rule’lar.`,
  activeProfile: 'Aktif analiz profili',
  profileRulesSummary: 'Aktif profil rule özeti',
  filteredRuleCount: (v) => `${v?.count ?? 0} rule gösteriliyor`,
  profileRuleCount: (v) => `Bu profilde ${v?.count ?? 0} aktif`,
  profileConfiguredRuleCount: (v) => `Bu profilde ${v?.count ?? 0} rule yapılandırılmış`,
  allSeverities: 'Tüm severity seviyeleri',
  allSources: 'Tüm kaynaklar',
  clearFilters: 'Filtreleri temizle',
  resizePanel: 'Paneli yeniden boyutlandır',
  resetPanelWidth: 'Panel genişliğini sıfırla',
  effectiveSeverity: 'Etkin severity',
  scoreImpact: 'Skor etkisi',
  maxPenaltyShort: (v) => `Maks. ${v?.value ?? 0}`,
  projectCompatibility: 'Proje uyumluluğu',
  allProjectTypes: 'Tüm proje tipleri',
  ruleCatalog: 'Rule Catalog',
  ruleManagement: 'Rule yönetimi',
  totalRules: 'Toplam Rule',
  totalRulesHint: 'Bu profildeki tüm rule’lar',
  enabledRules: 'Etkin Rule’lar',
  enabledRulesHint: 'Analiz sırasında denetlenir',
  disabledRules: 'Devre Dışı',
  disabledRulesHint: 'Geçici olarak hariç tutulur',
  customRulesHint: 'Kullanıcı tarafından oluşturulan',
  editProfile: 'Profili Düzenle',
  rulesWorkspaceHelp: 'Aktif profil rule’larını, skor ayarlarını ve proje uyumluluğunu tek yerde yönetin.',
  ruleCatalogLoadFailed: 'Rule Catalog yüklenemedi.',
  searchRules: 'Rule ara...',
  searchFindings: 'Bulgularda ara...',
  findingSort: 'Bulgu sıralaması',
  defaultOrder: 'Varsayılan sıra',
  severityHighToLow: 'Önem: yüksekten düşüğe',
  severityLowToHigh: 'Önem: düşükten yükseğe',
  allRules: 'Tüm rule’lar',
  allCategories: 'Tüm kategoriler',
  findingCategory: 'Bulgu kategorisi',
  projectProfileHint: 'Bu proje seçilen analiz profilini hatırlar.',
  categoryReliability: 'Reliability',
  categoryMaintainability: 'Maintainability',
  categoryPerformance: 'Performance',
  categorySecurity: 'Security',
  categoryExceptionHandling: 'Exception Handling',
  categoryNaming: 'Naming',
  categoryLogging: 'Logging',
  categoryUiAutomation: 'UI Automation',
  categoryArchitecture: 'Architecture',
  categoryConfiguration: 'Configuration',
  categoryOrchestrator: 'Orchestrator',
  enabled: 'Aktif',
  disabled: 'Pasif',
  source: 'Kaynak',
  builtIn: 'Built-in',
  custom: 'Custom',
  builtInRule: 'Built-in rule',
  customRule: 'Custom rule',
  ruleId: 'Rule ID',
  ruleName: 'Rule adı',
  severity: 'Severity',
  weight: 'Weight',
  fixSupport: 'Fix desteği',
  aggregationSupport: 'Aggregation desteği',
  selectRule: 'Detay için bir rule seçin.',
  loadingRules: 'Rule’lar yükleniyor...',
  exportRules: 'Rule Export',
  importRules: 'Rule Import',
  customRuleBuilder: 'Custom Rule Builder',
  createRule: 'Rule Oluştur',
  newCustomRule: 'Yeni Özel Rule',
  description: 'Açıklama',
  recommendation: 'Öneri',
  matchMode: 'Eşleşme modu',
  conditions: 'Koşullar',
  caseSensitive: 'Büyük/küçük harfe duyarlı',
  remove: 'Kaldır',
  addCondition: 'Koşul ekle',
  testRule: 'Rule Test Et',
  saveRule: 'Rule Kaydet',
  testing: 'Test ediliyor...',
  saving: 'Kaydediliyor...',
  customRuleNeedsProject: 'Bu rule’u test etmek için UiPath project path girin veya analiz çalıştırın.',
  customRuleTestCompleted: 'Custom rule testi tamamlandı.',
  customRuleTestFailed: 'Custom rule testi başarısız.',
  customRuleSaved: 'Custom rule kaydedildi.',
  customRuleSaveFailed: 'Custom rule kaydedilemedi.',
  ruleTemplates: 'Rule Şablonları',
  reuseRuleTemplate: 'Rule şablonu kullan',
  allTemplates: 'Tüm Şablonlar',
  builtInTemplates: 'Hazır Şablonlar',
  analysisProfileTemplates: 'Analiz Profili Şablonları',
  myTemplates: 'Şablonlarım',
  saveAsTemplate: 'Şablon Olarak Kaydet',
  templateSource: 'Şablon kaynağı',
  ruleTemplate: 'Şablon',
  ruleSource: 'Rule kaynağı',
  builtInRules: 'Hazır Rule’lar',
  customRules: 'Custom Rule’lar',
  noTemplate: 'Şablonsuz',
  noCustomTemplates: 'Henüz özel şablon oluşturulmadı.',
  noTemplatesMatchFilter: 'Bu filtreyle eşleşen şablon bulunamadı.',
  noActiveRulesMatchFilter: 'Bu filtreyle eşleşen aktif rule bulunamadı.',
  ruleTemplateSaved: (v) => v?.templateName ? `"${v.templateName}" rule şablonu başarıyla kaydedildi.` : 'Rule şablonu başarıyla kaydedildi.',
  ruleTemplateSaveFailed: 'Rule şablonu kaydedilemedi.',
  ruleTemplateDuplicate: 'Bu isimde bir rule şablonu zaten var.',
  dismissNotification: 'Bildirimi kapat',
  customRulesExported: 'Custom rule’lar export edildi.',
  customRulesImported: 'Custom rule’lar import edildi.',
  customRulesImportFailed: 'Custom rule import başarısız.',
  pasteCustomRulesJson: 'custom-rules JSON içeriğini yapıştırın.',
  ruleNoiseWarning: 'Bu rule çok fazla bulgu üretebilir.',
  testRuleResult: 'Rule Test Sonucu',
  customRuleMatches: (v) => `Bu rule ${v?.workflows ?? 0} workflow içinde ${v?.activities ?? 0} activity ile eşleşiyor. Tahmini bulgu: ${v?.findings ?? 0}.`,
  allProjects: 'Tüm projeler',
  historyProjectFilter: 'Geçmiş proje filtresi',
  projectHistoryOnly: 'Seçili projeye ait analiz kayıtları gösteriliyor.',
  notifications: 'Bildirimler',
  about: 'Hakkında',
  lightTheme: 'Light',
  darkTheme: 'Dark',
  systemTheme: 'System',
  aiReviewEnabled: 'AI Review etkin',
  autoReviewSummary: 'Review özetini otomatik üret',
  suggestedFixes: 'Fix önerileri',
  askProjectEnabled: 'Ask Project',
  selectorQuality: 'Selector kalitesi',
  exceptionHandling: 'Exception handling',
  logging: 'Logging',
  namingConvention: 'Naming convention',
  hardcodedValues: 'Hard-coded değerler',
  performance: 'Performance',
  maintainability: 'Maintainability',
  security: 'Security',
  reframeworkBestPractices: 'REFramework best practices',
  settingsNotice: 'Bu bölüm masaüstü MVP için hazırlandı; kalıcı tercihler sonraki sürümde profile bağlanabilir.',
  projectIntake: 'Proje seçimi',
  backendChecking: 'Backend kontrol ediliyor...',
  backendReady: (v) => `Backend hazır: ${v?.url ?? ''}`,
  backendUnavailable: 'RPA Dev Assistant backend başlatılamadı.',
  uipathProject: 'UiPath Project',
  browse: 'Gözat',
  browseTitleDesktop: 'UiPath proje klasörü seç',
  browseTitleBrowser: 'Gözat özelliği desktop app içinde kullanılabilir',
  analysisProfile: 'Analiz Profili',
  browserModeHint: 'Browser development mode: native klasör seçimi desktop app içinde kullanılabilir. Manuel path girişi çalışmaya devam eder.',
  noFolderSelected: 'Klasör seçilmedi',
  manualPathEntered: 'Manuel path girildi. Tam doğrulama analiz sırasında yapılır.',
  folderSelected: 'Klasör seçildi. project.json doğrulaması hazır.',
  folderSelectedProjectJson: 'Klasör seçildi. project.json bulundu.',
  notUipathProject: 'Bu klasör bir UiPath projesi gibi görünmüyor.',
  validationFailed: 'Klasör seçildi. Proje doğrulaması tamamlanamadı.',
  selectProjectFirst: 'Önce bir UiPath proje klasörü seçin veya girin.',
  backendNotReady: 'Backend henüz hazır değil.',
  analysisCompleted: 'Analiz tamamlandı.',
  folderSelectedBackendNotReady: 'Klasör seçildi. Backend proje doğrulaması için henüz hazır değil.',
  analysisFailed: 'Proje analizi başarısız oldu. Seçilen klasörü ve backend durumunu kontrol edin.',
  analyzeProject: 'Projeyi Analiz Et',
  dashboardAnalyzeProject: 'Dashboard birincil aksiyon',
  analyzing: 'Analiz ediliyor...',
  exportJson: 'JSON Dışa Aktar',
  exportHtml: 'HTML Dışa Aktar',
  exportPdf: 'PDF Dışa Aktar',
  exporting: 'Dışa aktarılıyor...',
  createReport: 'Rapor Oluştur',
  reportDialogTitle: 'Rapor Oluştur',
  reportExecutiveSummary: 'Yönetici Özeti',
  reportQualityScore: 'Kalite Skoru',
  reportWorkflowDetails: 'Workflow Detayları',
  reportAiRecommendations: 'AI Önerileri',
  reportFixSuggestions: 'Fix Önerileri',
  cancel: 'İptal',
  createHtmlReport: 'HTML Rapor Oluştur',
  runAiProjectReview: 'AI ile Projeyi İncele',
  staticAnalysisBeforeAi: 'AI inceleme başlatmadan önce statik analiz çalıştırın.',
  staticAnalysisBeforeAsk: 'Projeye soru sormadan önce statik analiz çalıştırın.',
  enterProjectQuestion: 'Önce bir proje sorusu girin.',
  aiAssistedAnswerCompleted: 'AI destekli cevap tamamlandı.',
  aiReviewCompleted: 'AI inceleme tamamlandı.',
  aiReviewFailed: 'AI inceleme başarısız oldu.',
  askProjectFailed: 'Projeye soru isteği başarısız oldu.',
  fixSuggestionGenerated: 'Fix önerisi üretildi.',
  fixSuggestionFailed: 'Fix önerisi başarısız oldu.',
  applyFixFailed: 'Fix uygulama başarısız oldu.',
  undoFailed: 'Undo başarısız oldu.',
  analysisBeforeExport: 'Rapor dışa aktarmadan önce analiz çalıştırın.',
  reportExportFailed: (v) => `${v?.format ?? 'Rapor'} dışa aktarımı başarısız oldu.`,
  analyzingWithAi: 'AI ile inceleniyor...',
  overview: 'Özet',
  changeHistory: 'Değişiklik Geçmişi',
  workflows: 'Workflowlar',
  report: 'Rapor',
  aiReview: 'AI İnceleme',
  askProject: 'Projeye Sor',
  processPddNav: 'Süreç ve PDD Analizi',
  processPddEyebrow: 'Süreç Anlama',
  processPddTitle: 'Süreç ve PDD Analizi',
  processPddHelp: 'Analiz edilen süreci anlayın, kanıta dayalı business rule’ları çıkarın ve seçilen PDD ile karşılaştırın.',
  processPddAnalyzeFirst: 'Önce analiz edilecek UiPath projesini seçin.',
  pddDocument: 'PDD Dokümanı',
  selectPdd: 'PDD dokümanı seçin',
  processPddSupportedFormats: 'Bu güvenli lokal sürümde TXT ve Markdown desteklenir. Kaynak doküman asla değiştirilmez.',
  processPddAnalyze: 'Süreç ve PDD’yi Analiz Et',
  processPddAnalyzing: 'Süreç ve PDD analiz ediliyor...',
  processPddFailed: 'Süreç ve PDD analizi başarısız oldu.',
  processPddReadOnly: 'Salt okunur karşılaştırma. Proje veya PDD dosyası değiştirilmez.',
  identifiedSystems: 'Tespit Edilen Sistemler',
  projectBusinessRules: 'Projedeki Business Rule’lar',
  pddBusinessRules: 'PDD Business Rule’ları',
  possiblyMissingRules: 'PDD’de Eksik Olabilecek Kurallar',
  processSummary: 'Süreç Özeti',
  systemsUsed: 'Kullanılan Sistemler',
  processSystem: 'Sistem',
  processSystemType: 'Tür',
  processEvidence: 'Kanıt',
  processUsedByWorkflows: 'Kullanan Workflow’lar',
  processFlow: 'Süreç Akışı',
  processFlowDisclaimer: 'Bu sıra static Invoke Workflow File ilişkilerini özetler. Runtime branch veya paralel çalışma sırası çıkarılmaz.',
  processFlowOmitted: '{count} ek çağrılan workflow kısa özet dışında bırakıldı.',
  evidenceBackedRules: 'Yalnızca workflow kanıtıyla desteklenen koşullar gösterilir.',
  processConfidence: 'Güven',
  processRuleStatus: 'Dokümantasyon durumu',
  allConfidence: 'Tüm güven seviyeleri',
  processAllWorkflows: 'Tüm workflow’lar',
  pddGapAnalysis: 'PDD Fark Analizi',
  gapAnalysisDisclaimer: 'Olası eksikler kesin dokümantasyon hatası değil, inceleme önerisidir.',
  processStatus: 'Durum',
  allStatuses: 'Tüm durumlar',
  possiblyMissingFromPdd: 'PDD’de Eksik Olabilir',
  possiblyDocumented: 'PDD’de Olabilir',
  needsReview: 'İnceleme Gerekli',
  documented: 'Dokümante Edilmiş',
  pddStatusPossiblyMissing: 'PDD’de Eksik Olabilir',
  pddStatusPossiblyDocumented: 'PDD’de Olabilir',
  pddStatusNeedsReview: 'İnceleme Gerekli',
  pddStatusDocumented: 'Dokümante Edilmiş',
  pddAdditionSuggestion: 'PDD’ye Ekleme Önerisi',
  matchedPddEvidence: 'Eşleşen PDD Kanıtı',
  noMatchingBusinessRules: 'Seçili filtrelerle eşleşen business rule bulunamadı.',
  noPddBusinessRules: 'Seçilen PDD içinde dokümante edilmiş business rule tespit edilmedi.',
  noEvidenceFound: 'Desteklenen bir kanıt tespit edilmedi.',
  projectOverview: 'Proje Özeti',
  grade: 'Not',
  critical: 'Kritik',
  high: 'Yüksek',
  medium: 'Orta',
  low: 'Düşük',
  passedChecks: 'Geçen Kontroller',
  project: 'Proje',
  activities: 'Aktiviteler',
  score: 'Skor',
  summary: 'Özet',
  profile: 'Profil',
  errors: 'Hata',
  warnings: 'Uyarı',
  suggestions: 'Öneri',
  reviewSummary: 'İnceleme Özeti',
  noIssuesSummary: 'Proje aktif deterministic review kurallarını geçti. Kritik bir bulgu görünmüyor.',
  reviewSummaryText: (v) => `Proje analiz edildi. Başlıca odak alanları ${v?.categories ?? 'maintainability ve reliability'}. Ayrıntılar için Bulgular sekmesini inceleyin.`,
  topIssues: 'Öne Çıkan Bulgular',
  workflowHealth: 'Workflow Sağlığı',
  noIssuesDetected: 'Aktif rule profile tarafından sorun tespit edilmedi.',
  all: 'Tümü',
  category: 'Kategori',
  dependencies: 'Dependencyler',
  configAnalysis: 'Config Analizi',
  configIntelligenceTitle: 'Config Intelligence',
  configIntelligenceHelp: 'Config.xlsx kullanımını analiz edin; kullanılmayan key’leri, eksik referansları ve güvenli hard-coded Config adaylarını bulun.',
  configReady: 'Config analiz edildi',
  configOverviewTitle: 'Analiz özeti',
  configOverviewHelp: 'Config kapsamını inceleyin ve ayrıntılar için ilgili sonuç alanını açın.',
  analyzedConfig: 'Analiz edilen workbook',
  reviewSelectedChanges: (v) => `Değişiklikleri incele (${v?.count ?? 0})`,
  selectedChangesSummary: (v) => `${v?.count ?? 0} seçili değişiklik bu önizlemeye dahil edilecek.`,
  refreshPreview: 'Önizlemeyi yenile',
  configAnalysisEmptyTitle: 'Henüz Config analizi yok',
  analyzeConfig: 'Config’i Analiz Et',
  configAnalysisCompleted: 'Config analizi tamamlandı.',
  configAnalysisFailed: 'Config analizi başarısız oldu.',
  configAnalysisEmpty: 'Seçili UiPath projesi için Config analizi çalıştırın.',
  configWorkbook: 'Config Workbook',
  configWorkbookAutoDetect: 'Config.xlsx otomatik tespit edilsin veya manuel seçin',
  configWorkbookHint: 'Data/Config.xlsx otomatik bulunsun istiyorsanız boş bırakın. Proje farklı bir Config konumu kullanıyorsa dosyayı seçin.',
  browseConfigWorkbook: 'Config workbook seç',
  configWorkbookSelected: 'Config workbook seçildi.',
  configBrowserFileHint: 'Browser modunda desktop dosya seçici yok. Config workbook path’ini manuel girin.',
  configWorkbookNotFound: 'Bu proje için Config.xlsx bulunamadı.',
  configInUse: (v) => `Kullanılan Config: ${v?.fileName ?? ''}`,
  selectedConfigInvalid: 'Seçilen Config dosyası okunamadı veya desteklenen Config yapısında değil.',
  configKeys: 'Config Key’leri',
  usedConfigKeys: 'Kullanılan Config Key’leri',
  configUsageGraph: 'Kullanım Grafiği',
  configUsageGraphHelp: 'Parsed workflow referanslarından Config key ile workflow/activity ilişkileri.',
  noConfigUsages: 'Config key kullanımı tespit edilmedi.',
  usageCount: (v) => `${v?.count ?? 0} kullanım`,
  configActivityCount: (v) => `${v?.count ?? 0} activity`,
  unusedConfig: 'Kullanılmayan Config',
  unusedConfigHelp: 'Buradaki key’ler Config içinde var ancak parsed workflow property veya expression verilerinde referanslanmadı. Silme işlemleri otomatik seçilmez.',
  searchUnusedConfig: 'Kullanılmayan Config key’lerinde ara...',
  showingUnusedConfig: (v) => `${v?.shown ?? 0} / ${v?.total ?? 0} kullanılmayan key gösteriliyor`,
  configSheetAndRow: (v) => `${v?.sheet ?? '-'} sheet · ${v?.row ?? '-'} satır`,
  noParsedConfigReference: 'Bu key için parsed workflow referansı bulunamadı.',
  missingConfig: 'Eksik Config',
  missingConfigHelp: 'Buradaki key’ler workflow’larda referanslanıyor ancak Config içinde yok.',
  hardcodedCandidates: 'Hard-coded Adaylar',
  hardcodedCandidatesHelp: 'Config’e taşınabilecek konservatif literal değer adayları. Hassas değerler redakte edilir ve plain Config için önerilmez.',
  changePreview: 'Değişiklik Önizleme',
  previewConfigChanges: 'Değişiklikleri Önizle',
  configPreviewReady: 'Config değişiklik önizlemesi hazır.',
  configPreviewInvalid: 'Config değişiklik önizlemesinde doğrulama sorunları var.',
  configPreviewFailed: 'Config değişiklik önizlemesi başarısız oldu.',
  runConfigAnalysisFirst: 'Önce Config analizi çalıştırın.',
  noUnusedConfig: 'Kullanılmayan Config key tespit edilmedi.',
  noMissingConfig: 'Eksik Config referansı tespit edilmedi.',
  noHardcodedCandidates: 'Hard-coded Config adayı tespit edilmedi.',
  noConfigPreview: 'Workbook üretmeden önce Config değişikliklerini seçip önizleyin.',
  configOutputPath: 'Çıktı Config yolu',
  configOutputPathRequired: 'Üretmeden önce çıktı Config yolunu seçin.',
  configBrowserOutputHint: 'Browser modunda desktop Save dialog yok. Çıktı yolunu manuel girin.',
  configOriginalUnchanged: 'Orijinal Config workbook asla değiştirilmez. Farklı Kaydet ile yeni workbook üretilir.',
  generateConfigWorkbook: 'Config Workbook Üret',
  configGenerateCompleted: 'Yeni Config dosyası başarıyla kaydedildi.',
  configGenerateFailed: 'Config workbook üretimi başarısız oldu.',
  configGeneratedAt: (v) => `Config workbook üretildi: ${v?.path ?? ''}.`,
  dependencyAnalysis: 'Dependency Analizi',
  dependencyAnalysisHelp: 'project.json ve parsed activity verilerinden offline-first package kullanım, risk ve compatibility sinyalleri.',
  usedDependencies: 'Kullanılan',
  uiPathDependencies: 'UiPath Package’ları',
  thirdPartyDependencies: 'Third-party',
  possiblyUnused: 'Kullanılmıyor Olabilir',
  potentialConflicts: 'Olası Uyumsuzluk',
  modernClassicMode: 'Modern / Classic Mod',
  searchPackages: 'Package ara...',
  package: 'Package',
  version: 'Version',
  usage: 'Kullanım',
  usedByWorkflows: 'Kullanan Workflowlar',
  dependencyDetail: 'Dependency Detayı',
  compatibilityStatus: 'Compatibility',
  versionStatus: 'Version Durumu',
  usedActivities: 'Kullanılan Activity’ler',
  noMappedActivities: 'Eşleşen activity bulunamadı.',
  noMappedWorkflows: 'Eşleşen workflow bulunamadı.',
  compatibilityNotes: 'Compatibility Notları',
  noDependencyRisks: 'Dependency risk notu yok.',
  noRelatedFindings: 'İlgili bulgu yok.',
  noDependencyAnalysis: 'Dependency analizi üretilemedi.',
  dependenciesUsed: 'Kullanılan Dependencyler',
  noDependenciesUsed: 'Bu workflow için dependency kullanımı eşleşmedi.',
  close: 'Kapat',
  flowchartConverter: 'Flowchart Dönüştürücü',
  standaloneTool: 'Bağımsız araç',
  flowchartConverterHelp: 'Tekil UiPath XAML dosyalarını analiz edin, Flowchart → Sequence dönüşümünü önizleyin ve dönüştürülmüş workflow’u yeni dosya olarak kaydedin.',
  conversionProgress: 'Flowchart dönüşüm adımları',
  converterStepSelect: 'Seç ve analiz et',
  converterStepSelectHint: 'XAML seçimi',
  converterStepSelectDescription: 'Bir veya daha fazla UiPath XAML dosyası seçin ve workflow yapısını analiz edin.',
  converterStepAssess: 'Uygunluğu incele',
  converterStepAssessHint: 'Karmaşıklığı kontrol et',
  converterStepAssessDescription: 'Dönüşüm öncesinde yapı, karmaşıklık, güven, risk ve desteklenmeyen pattern bilgilerini inceleyin.',
  converterStepPreview: 'Önizle ve kaydet',
  converterStepPreviewHint: 'Yeni dosya olarak kaydet',
  converterStepPreviewDescription: 'Mevcut Flowchart ile önerilen Sequence yapısını karşılaştırın ve kayıt konumunu seçin.',
  selectedFileCount: (v) => `${v?.count ?? 0} dosya seçildi`,
  xamlAnalysisCompleted: (v) => `${v?.count ?? 0} XAML dosyası başarıyla analiz edildi.`,
  assessmentReasons: 'Değerlendirme nedenleri',
  flowchartReasonLinear: 'Flowchart doğrusal yapıdadır; cycle veya erişilemeyen node içermez.',
  flowchartReasonSimpleDecision: 'Flowchart basit ve döngüsüz bir decision yapısına sahiptir.',
  flowchartReasonReviewBranches: 'Flowchart önizlenebilir; ancak branch ve merge davranışı UiPath Studio içinde kontrol edilmelidir.',
  flowchartReasonLoopReview: 'Flowchart loop veya geri dönüşlü kontrol akışı içeriyor; dönüşüm sonrasında dikkatle incelenmelidir.',
  flowchartRiskCycle: 'Cycle tespit edildi. Flowchart cycle yapıları While, Retry veya goto benzeri bir kontrol akışını temsil edebilir.',
  flowchartRiskUnreachable: 'Flowchart başlangıç node’undan erişilemeyen bir node tespit edildi.',
  flowchartRiskMultipleEntries: (v) => `Birden fazla giriş benzeri node tespit edildi: ${v?.count ?? 0}.`,
  flowchartUnsupportedNoNodes: 'Flowchart node’ları parse edilemedi.',
  flowchartUnsupportedDecisionTarget: (v) => `${v?.node ?? '-'} node’u için FlowDecision branch hedefleri çözümlenemedi.`,
  flowchartUnsupportedSwitchTarget: (v) => `${v?.node ?? '-'} node’u için FlowSwitch case hedefleri çözümlenemedi.`,
  flowchartUnsupportedNodeCount: (v) => `Desteklenmeyen Flowchart node sayısı: ${v?.count ?? 0}.`,
  flowchartNestedMessage: (v) => `${v?.structure ?? '-'} workflow içinde nested Flowchart tespit edildi. Üretilen preview’ı production kullanımından önce dikkatle inceleyin.`,
  flowchartStepCreateSequence: 'Bir Sequence root oluşturun.',
  flowchartStepPreserveContent: 'Workflow argument, variable, activity property ve expression değerlerini koruyun.',
  flowchartStepMoveActivities: 'Doğrusal FlowStep activity’lerini Sequence sırasına taşıyın.',
  flowchartStepDecision: 'FlowDecision branch’lerini If preview node’ları olarak oluşturun.',
  flowchartStepSwitch: 'FlowSwitch branch’lerini Switch preview node’ları olarak oluşturun.',
  flowchartStepMerge: 'Ortak merge node’larını branch preview’larından sonra devam activity’leri olarak koruyun.',
  flowchartStepLoop: 'Tanınan geri dönüş loop’larını While preview node’ları olarak oluşturun ve UiPath Studio içinde kontrol edin.',
  flowchartStepExcludeComments: 'CommentOut içindeki yorumlanmış activity bloklarını üretilen Sequence’e taşımayın.',
  flowchartNestedDetected: 'Flowchart olmayan bir workflow içinde nested Flowchart tespit edildi.',
  flowchartRootOnlySupported: 'Otomatik dönüşüm şu anda yalnızca root activity’si Flowchart olan workflow’ları destekler.',
  selectAndAnalyzeBeforePreview: 'Dönüşüm önizlemesi oluşturmak için bir XAML dosyası seçip analiz edin.',
  xamlFilePath: 'XAML Dosya Yolu',
  selectXamlFirst: 'Önce bir UiPath .xaml dosyası seçin veya yol girin.',
  selectXamlFile: 'XAML Dosyası Seç',
  noXamlFileSelected: 'XAML dosyası seçilmedi',
  xamlFileSelected: 'XAML dosyası seçildi',
  analyzeXaml: 'XAML Analiz Et',
  selectedXamlFiles: 'Seçilen XAML Dosyaları',
  flowchartConverterEmpty: 'Flowchart dönüşüm uygunluğunu incelemek için bir veya daha fazla .xaml workflow dosyası seçin.',
  standaloneContext: 'Bağımsız Context',
  standaloneBrowserModeHint: 'Browser modunda native dosya penceresi açılamaz. Backend bu path’e erişebiliyorsa manuel dosya yolu girişi çalışır.',
  standaloneFlowchartAnalyzeFailed: 'Bağımsız Flowchart analizi başarısız oldu.',
  standaloneFlowchartConvertFailed: 'Bağımsız Flowchart dönüşümü başarısız oldu.',
  flowchartConverterDetail: 'Flowchart dönüştürücü detayı',
  originalFileNotModified: 'Bu bağımsız akışta orijinal XAML dosyası asla değiştirilmez.',
  saveConvertedWorkflowAs: 'Dönüştürülmüş Workflow’u Farklı Kaydet...',
  outputXamlPath: 'Çıktı XAML yolu',
  chooseOutputPath: 'Kaydetme Konumu Seç',
  chooseOutputPathFirst: 'Dönüştürülmüş .xaml dosyasının nereye kaydedileceğini seçin.',
  outputXamlPathRequired: 'Dönüştürmeden önce çıktı XAML yolunu seçin.',
  convertAndSave: 'Dönüştür ve Kaydet',
  convertedWorkflowSaved: 'Dönüştürülmüş workflow başarıyla kaydedildi.',
  conversionNotAvailable: 'Bu dosya için dönüşüm kullanılamıyor',
  conversionNotAvailableReason: 'Bu workflow bağımsız dönüştürücü tarafından güvenli şekilde dönüştürülemiyor.',
  conversionNotAvailableNestedReason: 'Başka bir workflow yapısının içinde Flowchart tespit edildi. Farklı Kaydet yalnızca bu nested Flowchart çevresindeki workflow root yapısını değiştirmeden güvenli şekilde dönüştürülebiliyorsa açılır.',
  detectedFlowchartNodes: 'Tespit Edilen Flowchart Node’ları',
  standaloneFlowchartStatusReady: 'Hazır',
  standaloneFlowchartStatusAlreadySequence: 'Zaten Sequence',
  standaloneFlowchartStatusRequiresReview: 'İnceleme Gerektiriyor',
  standaloneFlowchartStatusComplex: 'Karmaşık',
  standaloneFlowchartStatusUnsupported: 'Desteklenmiyor',
  standaloneFlowchartStatusConverted: 'Dönüştürüldü',
  standaloneFlowchartStatusFailed: 'Başarısız',
  xamlPathRequired: 'Önce bir XAML dosya yolu girin.',
  visualWorkflowPreview: 'Görsel Akış Önizlemesi',
  visualFlow: 'Görsel Akış',
  xamlCodePreview: 'XAML Kod Önizlemesi',
  activitiesToUse: 'Kullanılacak Aktiviteler',
  activitiesUsedCount: (v) => `Sequence içinde ${v?.count ?? 0} aktivite`,
  copyXamlCode: 'XAML Kopyala',
  copiedToClipboard: 'Panoya kopyalandı!',
  workflowTargetSequence: 'Hedef: Sequence Yapısı',
  activitySourceNode: 'Kaynak Node',
  activityRole: 'Rol',
  executableActivity: 'Çalıştırılabilir Aktivite',
  containerActivity: 'Konteyner',
  controlFlowActivity: 'Kontrol Akışı',
  customDependencyDetected: 'Özel Bağımlılık Aktiviteleri Tespit Edildi',
  customDependencyNotice: (v) => `Bu Flowchart içinde ${v?.count ?? 0} özel / üçüncü taraf bağımlılığa ait aktivite tespit edildi.`,
  replaceWithStandardUiPath: 'Önerilen Standart UiPath Aktiviteleriyle Değiştir',
  replaceWithStandardUiPathHelp: 'Seçildiğinde, özel bağımlılık aktiviteleri üretilen XAML içinde yerel UiPath aktiviteleriyle değiştirilir.',
  suggestedReplacement: 'Önerilen Standart Aktivite',
  customActivityName: 'Özel Aktivite',
  suggestedPackage: 'Gerekli UiPath Paketi',
  replacementReason: 'Gerekçe / Eşleme',
  flowchartConversionSummary: 'Dönüşüm Özeti',
  structureType: 'Yapı Tipi',
  containsFlowchart: 'Flowchart İçeriyor',
  flowchartCount: 'Flowchart Sayısı',
  flowchartConversion: 'Flowchart Dönüşümü',
  previewConversion: 'Dönüşüm Önizle',
  copyPlan: 'Planı Kopyala',
  conversionPreviewOnly: 'Salt okunur dönüşüm önizlemesi. Hiçbir XAML dosyası değiştirilmeyecek.',
  nestedFlowchartConversionNotSupported: 'Nested Flowchart tespit edildi. Otomatik dönüşüm şu anda yalnızca workflow root öğesi Flowchart olduğunda kullanılabilir.',
  flowchartConversionFailed: 'Flowchart dönüşüm analizi başarısız oldu.',
  currentStructure: 'Mevcut Yapı',
  convertibility: 'Dönüştürülebilirlik',
  nodes: 'Node Sayısı',
  decisions: 'Decision Sayısı',
  switches: 'Switch Sayısı',
  cycles: 'Döngüler',
  unreachableNodes: 'Erişilemeyen Node',
  currentFlowchart: 'Mevcut Flowchart',
  proposedSequence: 'Önerilen Sequence',
  noPreviewAvailable: 'Dönüşüm önizlemesi üretilemedi.',
  noRisks: 'Dönüşüm riski tespit edilmedi.',
  unsupportedPatterns: 'Desteklenmeyen Patternler',
  noUnsupportedPatterns: 'Desteklenmeyen pattern tespit edilmedi.',
  conversionMappings: 'Dönüşüm Eşlemeleri',
  sourceNode: 'Kaynak Node',
  targetPath: 'Hedef Path',
  flowchartLevelSafe: 'Güvenli',
  flowchartLevelRequiresReview: 'İnceleme Gerektiriyor',
  flowchartLevelComplex: 'Karmaşık',
  flowchartLevelNotSupported: 'Desteklenmiyor',
  flowchartConfidenceHigh: 'Yüksek',
  flowchartConfidenceMedium: 'Orta',
  flowchartConfidenceLow: 'Düşük',
  applyConversion: 'Dönüşümü Uygula',
  confirmConversion: 'Dönüşümü Onayla',
  rollback: 'Geri Al',
  rollingBack: 'Geri alınıyor...',
  conversionApplyWarning: 'Bu işlem workflow XAML dosyasını değiştirecek. İşlemden önce otomatik yedek oluşturulacaktır.',
  conversionBackupWillBeCreated: 'Workflow değiştirilmeden önce otomatik yedek oluşturulacak.',
  conversionManualReviewOnly: 'Bu dönüşüm yalnızca önizleme modunda; Flowchart manuel inceleme gerektiriyor veya otomatik uygulama için desteklenmiyor.',
  manualReviewRequired: 'Manuel inceleme gerekli',
  flowchartConversionApplyFailed: 'Flowchart dönüşüm uygulaması başarısız oldu.',
  flowchartConversionRollbackFailed: 'Flowchart dönüşüm geri alma başarısız oldu.',
  conversionAppliedSuccessfully: 'Flowchart dönüşümü başarıyla uygulandı.',
  conversionWasNotApplied: 'Flowchart dönüşümü uygulanmadı.',
  conversionRolledBackSuccessfully: 'Dönüşüm başarıyla geri alındı.',
  showingFindings: (v) => `${v?.shown ?? 0} / ${v?.total ?? 0} bulgu gösteriliyor`,
  noFilteredFindings: 'Önemli bir sorun tespit edilmedi veya mevcut filtre bulgu döndürmedi.',
  showMoreFindings: (v) => `Daha fazla göster (${v?.remaining ?? 0} kaldı)`,
  affectedActivities: 'etkilenen aktivite',
  relevantActivities: 'ilgili aktivite',
  fixSuggestion: 'Fix Önerisi',
  rule: 'Rule',
  reviewLowConfidenceFix: 'Değişiklik yapmadan önce bu öneriyi dikkatlice inceleyin.',
  aiSuggestionManualReview: 'AI önerisi — manuel inceleme gerekli.',
  fixSuggestionStale: 'Fix önerisi üretildi ancak stale olabilir.',
  applying: 'Uygulanıyor...',
  applyFix: 'Fix Uygula',
  fixAppliedSuccessfully: 'Fix başarıyla uygulandı.',
  fixWasNotApplied: 'Fix uygulanmadı.',
  backupCreated: 'Backup oluşturuldu',
  projectFilesChangedReanalysis: 'Proje dosyaları değişti. Bulguları yenilemek için analizi yeniden çalıştırın.',
  applyThisChange: 'Bu değişiklik uygulansın mı?',
  property: 'Property',
  unknown: 'Bilinmiyor',
  backupWillBeCreated: 'Dosya değiştirilmeden önce backup oluşturulacak.',
  generating: 'Üretiliyor...',
  suggestedFix: 'Önerilen Fix',
  noFixAvailable: 'Bu bulgu için henüz otomatik fix önerisi yok.',
  aiFixPrivacy: 'Yapılandırılmış AI provider’a küçültülmüş ve redakte edilmiş workflow context gönderilecek.',
  generateAiSuggestion: 'AI destekli öneri üret',
  fixType: 'Fix Türü',
  fixability: 'Fix Durumu',
  risk: 'Risk',
  confidence: 'Güven',
  aiAssisted: 'AI Destekli',
  autoApply: 'Auto Apply',
  yes: 'Evet',
  no: 'Hayır',
  available: 'Kullanılabilir',
  previewOnly: 'Sadece preview',
  before: 'ÖNCE',
  after: 'SONRA',
  why: 'Neden?',
  steps: 'Adımlar',
  risks: 'Riskler',
  userInputNeeded: 'Kullanıcı Kararı Gerekli',
  validationNotes: 'Doğrulama Notları',
  copyFixInstructions: 'Fix talimatlarını kopyala',
  manualChangeRequired: 'Manuel değişiklik gerekli.',
  highRiskFix: 'Bu öneri workflow davranışını etkileyebilir. UiPath Studio içinde dikkatlice inceleyin.',
  noBeforePreview: 'Önceki durum preview’i yok.',
  noAfterPreview: 'Sonraki durum preview’i yok.',
  workflowCountFound: (v) => `${v?.count ?? 0} Workflow Bulundu`,
  workflowListHelp: 'Workflow listesini arayın, filtreleyin ve detaylarını inceleyin.',
  searchWorkflows: 'Workflow ara...',
  byFindings: 'Bulguya göre',
  byActivity: 'Aktiviteye göre',
  byName: 'Ada göre',
  workflowName: 'Workflow Adı',
  type: 'Tür',
  activity: 'Aktivite',
  status: 'Durum',
  good: 'İyi',
  reviewNeeded: 'İncelenmeli',
  risky: 'Riskli',
  workflowDetail: 'Workflow detayı',
  backToWorkflows: 'Workflowlara Dön',
  fileName: 'Dosya Adı',
  relativePath: 'Relative Path',
  activityCount: 'Activity Count',
  executableActivityCount: 'Executable Activity Count',
  findingCount: 'Bulgu Sayısı',
  arguments: 'Arguments',
  noArguments: 'Bu workflow için argument bulunamadı.',
  direction: 'Yön',
  name: 'Ad',
  invokedWorkflows: 'Çağrılan Workflowlar',
  noInvokes: 'Bu workflow doğrudan başka bir workflow çağırmıyor.',
  dynamicWorkflowReference: 'Dinamik workflow referansı',
  calledBy: 'Çağıran Workflowlar',
  noCallers: 'Bu workflow başka bir workflow tarafından çağrılmıyor.',
  activityTypes: 'Activity Türleri',
  activityTree: 'Activity Tree',
  noActivities: 'Bu workflow için parse edilmiş activity bulunamadı.',
  selectedActivity: 'Seçili Activity',
  properties: 'Properties',
  relatedFindings: 'İlgili Bulgular',
  workflowFindings: 'Workflow Bulguları',
  noWorkflowFindings: 'Bu workflow ile ilişkili bulgu yok.',
  reviewWorkflowWithAi: 'AI ile Workflow İncele',
  aiNotConfigured: 'AI İnceleme yapılandırılmamış.',
  aiPanelTitle: 'Bu proje hakkında soru sorun veya AI destekli inceleme başlatın.',
  aiReviewInterpretationNotice: 'AI review ek yorum ve öneriler sağlar. Deterministic statik analiz bulguları rule-based sorunlar için ana kaynak olmaya devam eder.',
  aiReviewPrivacyNotice: 'AI Review yapılandırılmış AI provider’a küçültülmüş, redakte edilmiş proje özetini gönderir.',
  aiReviewEmptyState: 'AI proje incelemesi çalıştırın veya Workflows sekmesinden bir workflow seçin.',
  aiQuickRiskSummary: 'En büyük riskleri özetle',
  aiQuickRefactorWorkflows: 'Hangi workflow’lar refactor edilmeli?',
  aiQuickSelectors: 'Selector problemlerini göster',
  aiQuickExceptionHandling: 'Exception handling sorunlarını bul',
  aiQuickMaintainability: 'Proje bakım kalitesini nasıl artırabilirim?',
  aiQuickTopFindings: 'En kritik 5 bulguyu açıkla',
  riskLevel: 'Risk Seviyesi',
  scope: 'Kapsam',
  model: 'Model',
  aiReviewSummary: 'AI İnceleme Özeti',
  strengths: 'Güçlü Yönler',
  issues: 'Sorunlar',
  noAiIssues: 'AI issue dönmedi.',
  evidenceLabel: 'Evidence',
  relatedDeterministicRules: 'İlgili deterministic rule’lar',
  recommendations: 'Öneriler',
  architectureObservations: 'Mimari Gözlemler',
  noItemsReturned: 'Öğe dönmedi.',
  askNotice: 'Doğrudan proje sorguları lokal analizden cevaplanır. Yorum gerektiren sorularda yapılandırılmış AI provider’a küçültülmüş ve redakte edilmiş evidence gönderilebilir.',
  askLabel: 'UiPath projenize sorun',
  askPlaceholder: 'Exception handling açısından en riskli workflow hangisi?',
  ask: 'Sor',
  asking: 'Soruluyor...',
  suggestedQuestions: 'Önerilen Sorular',
  suggestedQueueQuestion: 'Bu projede Queue nerede kullanılıyor?',
  suggestedDelayQuestion: 'Hangi workflowlarda Delay var?',
  suggestedMostFindingsQuestion: 'En fazla finding hangi workflow’da?',
  suggestedProcessQuestion: 'Process.xaml dosyasını açıkla',
  suggestedInvocationQuestion: 'Workflow çağrı ilişkilerini göster',
  suggestedExceptionQuestion: 'Exception handling sorunu olan workflow’ları göster',
  answer: 'Cevap',
  questionConfidence: 'Güven',
  aiUsed: 'AI Kullanıldı',
  answeredLocal: 'Lokal proje analizinden cevaplandı',
  aiAnswerBased: 'Getirilen proje evidence’ına dayalı AI destekli cevap',
  evidence: 'Evidence',
  relatedWorkflows: 'İlgili Workflowlar',
  relatedRules: 'İlgili Rulelar',
  reasoningSummary: 'Akıl Yürütme Özeti',
  value: 'Değer',
  current: 'Mevcut',
  restore: 'Geri Yüklenecek',
  undo: 'Geri Al',
  undoUnavailable: 'Undo kullanılamıyor.',
  undoThisChange: 'Bu değişiklik geri alınsın mı?',
  undoChange: 'Değişikliği Geri Al',
  undoing: 'Geri alınıyor...',
  changeRestoredSuccessfully: 'Değişiklik başarıyla geri yüklendi.',
  changeWasNotRestored: 'Değişiklik geri yüklenmedi.',
  safetyBackupCreated: 'Safety backup oluşturuldu',
  reanalysisRequired: 'Yeniden analiz gerekli.',
  noFixHistory: 'Bu proje için RPA Dev Assistant fix geçmişi bulunamadı.',
  analysisHistory: 'Analiz Geçmişi',
  allProjectsHistory: 'Değerlendirilen tüm projelerin analiz kayıtları gösteriliyor.',
  noAnalysisHistory: 'Bu proje için kayıtlı analiz snapshot’ı bulunamadı.',
  comparePrevious: 'Öncekiyle Karşılaştır',
  noPreviousSnapshot: 'Önceki snapshot yok',
  beforeAfterComparison: 'Önce / Sonra Karşılaştırma',
  scoreChange: 'Skor Değişimi',
  findingChange: 'Finding Değişimi',
  newFindings: 'Yeni Findingler',
  resolvedFindings: 'Kapanan Findingler',
  unchangedFindings: 'Değişmeyen Findingler',
  changedFindings: 'Değişen Findingler',
  workflowChanges: 'Workflow Değişimleri',
  noWorkflowChanges: 'Workflow seviyesinde değişim tespit edilmedi.',
  activityChange: 'Activity Değişimi',
  complexityChange: 'Complexity Değişimi',
  fixHistory: 'Fix Geçmişi',
  analysisHistoryLoadFailed: 'Analiz geçmişi yüklenemedi.',
  analysisComparisonFailed: 'Analiz karşılaştırması oluşturulamadı.',
  none: 'Yok',
  loading: 'Yükleniyor...',
  refresh: 'Yenile',
  applied: 'Uygulandı',
  unknownWorkflow: 'Bilinmeyen workflow',
  unknownRule: 'Bilinmeyen rule',
  analysisOutOfDate: 'Analiz güncel değil.',
  analysisOutOfDateDetail: 'Proje dosyaları değişti. Bulguları ve kalite skorunu yenilemek için analizi yeniden çalıştırın.',
  rerunAnalysis: 'Analizi Yeniden Çalıştır',
  reportNotice: 'HTML ve JSON export mevcut rapor altyapısını kullanır. PDF export bu sürümde pasif bırakıldı.',
  locale: 'Dil',
  greeting: 'İyi akşamlar, Mina',
  openProject: 'Proje Aç',
  reviewedProjects: 'İncelenen Proje',
  openFindings: 'Açık Bulgu',
  averageQualityScore: 'Ortalama Kalite Skoru',
  recentProjects: 'Son Projeler',
  projectColumn: 'PROJE',
  platformColumn: 'PLATFORM',
  lastReviewColumn: 'SON İNCELEME',
  qualityScoreColumn: 'KALİTE SKORU',
  findingsColumn: 'BULGULAR',
  statusColumn: 'DURUM',
  todayTime: 'Bugün 14:32',
  yesterday: 'Dün',
  complexity: 'Karmaşıklık',
  workflowComplexity: 'Workflow Karmaşıklığı',
  complexityDistribution: 'Karmaşıklık Dağılımı',
  topComplexWorkflows: 'En Karmaşık Workflowlar',
  complexityScore: 'Karmaşıklık Skoru',
  complexityLevel: 'Karmaşıklık Seviyesi',
  maxNestingDepth: 'Maksimum İç İçe Geçme Derinliği',
  decisionCount: 'Karar Sayısı',
  loopCount: 'Loop Sayısı',
  tryCatchCount: 'Try/Catch Sayısı',
  invokeWorkflowCount: 'Invoke Workflow Sayısı',
  containerActivityCount: 'Container Activity Sayısı',
  whyThisScore: 'Bu skor neden?',
  rawPenalty: 'Ham Ceza',
  normalizedPenalty: 'Normalize Ceza',
  projectSizeFactor: 'Proje Boyut Faktörü',
  appliedPenalty: 'Uygulanan Ceza',
  maxPenalty: 'Maksimum Ceza',
  occurrenceCount: 'Occurrence',
  veryHigh: 'Çok Yüksek',
  profileLoadFailed: 'Rule profile listesi yüklenemedi.',
  customRuleProfiles: 'Custom Rule Profile’ları',
  profileBuilder: 'Profile Builder',
  exportProfiles: 'Profile Export',
  saveProfile: 'Profile Kaydet',
  profileId: 'Profile ID',
  profileName: 'Profile Adı',
  profileTemplate: 'Profile Şablonu',
  selectProfileTemplate: 'Profile şablonu seç',
  severityOverride: 'Severity Override',
  defaultSeverity: 'Varsayılan Severity',
  namingConventionSettings: 'İsimlendirme standardı ayarları',
  namingPattern: 'İsimlendirme deseni',
  namingPatternPlaceholder: 'Regular expression, örneğin ^[A-Z][A-Za-z0-9]*$',
  requiredPrefix: 'Zorunlu prefix',
  inArgumentPrefix: 'In argument prefix',
  outArgumentPrefix: 'Out argument prefix',
  inOutArgumentPrefix: 'In/Out argument prefix',
  ruleProfileSaved: 'Rule profile kaydedildi.',
  ruleProfileSaveFailed: 'Rule profile kaydedilemedi.',
  ruleProfilesExported: 'Rule profile’ları export edildi.',
  ruleNameEn: 'Rule Adı (EN)',
  ruleNameTr: 'Rule Adı (TR)',
  descriptionEn: 'Açıklama (EN)',
  descriptionTr: 'Açıklama (TR)',
  recommendationEn: 'Öneri (EN)',
  recommendationTr: 'Öneri (TR)',
  propertyName: 'Property Adı',
  compareValue: 'Karşılaştırma Değeri',
};

export const translations = { en, tr };

export function translate(locale: Locale, key: string, values?: Record<string, unknown>): string {
  const value = translations[locale][key] ?? translations.en[key] ?? key;
  return typeof value === 'function' ? value(values) : value;
}

const ruleTranslations: Record<Locale, Record<string, Partial<{ name: string; message: string; recommendation: string }>>> = {
  en: {},
  tr: {
    RPA001: {
      name: 'Delay Activity kullanımından kaçının',
      message: 'Delay activity tespit edildi. Mümkünse state-based bekleme mekanizmalarını tercih edin.',
      recommendation: 'Check App State, Retry Scope, Element Exists veya timeout tabanlı UI activity kullanın.',
    },
    RPA003: {
      name: 'Exception sessizce yutuluyor',
      message: 'Catch bloğunda exception loglanmıyor, Throw veya Rethrow ile yeniden fırlatılmıyor.',
      recommendation: 'Catch içinde Log Message ekleyin ve exception propagate edilmeli mi açıkça karar verin.',
    },
    RPA005: {
      name: 'Geçersiz Invoke Workflow referansı',
      message: 'Invoke Workflow File projede bulunmayan bir workflow’a referans veriyor.',
      recommendation: 'Referans verilen workflow path’ini doğrulayın veya doğru relative path ile güncelleyin.',
    },
    RPA006: {
      name: 'Workflow isimlendirme standardı',
      message: 'Workflow dosya adı generic veya standarda aykırı görünüyor.',
      recommendation: 'Workflow dosyasını amacını anlatan PascalCase bir isimle adlandırın.',
    },
    RPA007: {
      name: 'Generic activity DisplayName',
      message: 'Workflow içinde generic activity DisplayName değerleri tespit edildi.',
      recommendation: 'DisplayName değerlerini activity’nin business amacını anlatacak şekilde güncelleyin.',
    },
    RPA008: {
      name: 'Workflow içinde logging yok',
      message: 'Yeterince büyük workflow içinde Log Message activity bulunamadı.',
      recommendation: 'Workflow başlangıcı, kritik adımlar ve tamamlanma noktalarına anlamlı Log Message ekleyin.',
    },
    RPA013: {
      name: 'ContinueOnError aktif',
      message: 'Executable activity üzerinde ContinueOnError=True tespit edildi.',
      recommendation: 'Hataları global olarak bastırmak yerine beklenen exception’ları açıkça yönetin.',
    },
    RPA015: {
      name: 'Kritik UI activity için explicit timeout yok',
      message: 'UI automation activity üzerinde explicit timeout property bulunamadı.',
      recommendation: 'Gerekliyse gerçekçi ve configurable timeout değerleri kullanın.',
    },
    RPA017: {
      name: 'Selector idx attribute kullanıyor',
      message: 'Selector içinde idx attribute kullanımı tespit edildi.',
      recommendation: 'Mümkünse idx yerine daha stabil semantic attribute’lar kullanın.',
    },
    RPA020: {
      name: 'Hard-coded absolute file path',
      message: 'Hard-coded absolute file path tespit edildi.',
      recommendation: 'Ortama bağlı path değerlerini configuration içine taşıyın.',
    },
    RPA024: {
      name: 'Çok fazla workflow argument’i',
      message: 'Workflow argument sayısı eşik değeri aşıyor.',
      recommendation: 'İlişkili verileri model içinde gruplayın veya workflow sorumluluğunu azaltın.',
    },
    RPA025: {
      name: 'Büyük workflow',
      message: 'Workflow çok fazla executable activity içeriyor.',
      recommendation: 'Büyük workflow’ları daha küçük ve odaklı reusable component’lara bölün.',
    },
  },
};

export function localizeFinding<T extends { ruleId: string; ruleName?: string; message?: string; recommendation?: string | null }>(finding: T, locale: Locale): T {
  if (locale === 'en') {
    return finding;
  }

  const rule = ruleTranslations[locale][finding.ruleId];
  if (!rule) {
    return finding;
  }

  return {
    ...finding,
    ruleName: rule.name ?? finding.ruleName,
    message: rule.message ?? finding.message,
    recommendation: rule.recommendation ?? finding.recommendation,
  } as T;
}
